apiVersion: apps/v1
kind: Deployment
metadata:
  name: rekor-server
  namespace: rekor-system
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: scaffold
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: rekor
    helm.sh/chart: rekor-1.0.3
    pod-template-hash: 5c755b56f9
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: server
      app.kubernetes.io/instance: scaffold
      app.kubernetes.io/name: rekor
      helm.sh/chart: rekor-1.0.3
      pod-template-hash: 5c755b56f9
  template:
    metadata:
      labels:
        app.kubernetes.io/component: server
        app.kubernetes.io/instance: scaffold
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: rekor
        helm.sh/chart: rekor-1.0.3
        pod-template-hash: 5c755b56f9
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "2112"
        prometheus.io/scrape: "true"
    spec:
      containers:
        - name: rekor-server
          args:
            - serve
            - --trillian_log_server.address=trillian-logserver-pod
            - --trillian_log_server.port=8091
            - --trillian_log_server.sharding_config=/sharding/sharding-config.yaml
            - --redis_server.address=rekor-redis
            - --redis_server.port=6379
            - --rekor_server.address=0.0.0.0
            - --rekor_server.signer=memory
            - --enable_retrieve_api=true
            - --trillian_log_server.tlog_id={{ trillian_tree_id }}
            - --enable_attestation_storage
            - --attestation_storage_bucket=file:///var/run/attestations
          image: {{ tas_single_node_rekor_image }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              protocol: TCP
              hostPort: 3000
            - containerPort: 2112
              protocol: TCP
              hostPort: 2112
          resources: {}
          volumeMounts:
            - mountPath: /sharding
              name: rekor-sharding-config
            - mountPath: /var/run/attestations
              name: storage
      restartPolicy: Always
      volumes:
        - name: rekor-sharding-config
          configMap:
            defaultMode: 420
            name: rekor-sharding-config
        - name: storage
          persistentVolumeClaim:
            claimName: rekor-server

