---

- name: Create Trillian Secret
  containers.podman.podman_secret:
    name: trillian-mysql
    state: present
    force: true
    data: "{{ trillian_mysql_secret | to_json }}"
  vars:
    trillian_mysql_secret:
      "mysql-root-password": "{{ trillian.mysql.rootPassword | b64encode }}"
      "mysql-password": "{{ trillian.mysql.password | b64encode }}"
      "mysql-database": "{{ trillian.mysql.database | b64encode }}"
      "mysql-user": "{{ trillian.mysql.user | b64encode }}"

- name: Build Trillian Database Manifest specs
  ansible.builtin.include_tasks: podman/install_manifest.yml
  vars:
    podman_spec:
      state: "started"
      systemd_file: "trillian-mysql"
      network: "{{ sigstore_podman_network }}"
      kube_file_content: "{{ lookup('ansible.builtin.template', 'manifests/trillian/trillian-mysql.yaml') | from_yaml }}"

- name: Build Trillian Log Signer Manifest specs
  ansible.builtin.include_tasks: podman/install_manifest.yml
  vars:
    podman_spec:
      state: "started"
      systemd_file: "trillian-signer"
      network: "{{ sigstore_podman_network }}"
      kube_file_content: "{{ lookup('ansible.builtin.template', 'manifests/trillian/trillian-logsigner.yaml') | from_yaml }}"

- name: Build Trillian Log Server Manifest specs
  ansible.builtin.include_tasks: podman/install_manifest.yml
  vars:
    podman_spec:
      state: "started"
      systemd_file: "trillian-server"
      network: "{{ sigstore_podman_network }}"
      kube_file_content: "{{ lookup('ansible.builtin.template', 'manifests/trillian/trillian-logserver.yaml') | from_yaml }}"
