issuer: https://dex-idp:5556/dex

storage:
  type: memory

web:
  https: 0.0.0.0:5556
  tlsCert: /etc/dex/cfg/tls.crt
  tlsKey: /etc/dex/cfg/tls.key

staticClients:
- id: trusted-artifact-signer
  redirectURIs:
  - 'https://dex-idp:5556/callback'
  name: 'Trusted Artifact Signer'
  secret: ZXhhbXBsZS1hcHAtc2VjcmV0

enablePasswordDB: true

staticPasswords:
- email: "admin@example.com"
  hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
  username: "admin"
  userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"
- email: "jdoe@redhat.com"
  hash: "$2y$10$hUQg/726r34CrnMKx0iBde3luhdxb6elLqLjO4AVlu2psmnQOXXR2" # secure
  username: "jdoe"
  userID: "123456"

oauth2:
  responseTypes: ["code"]
  alwaysShowLoginScreen: true
  skipApprovalScreen: true
  passwordConnector: local

expiry:
  signingKeys: "24h"
  idTokens: "10m"
  authRequests: "24h"
