apiVersion: apps/v1
kind: Deployment
metadata:
  name: rekor-redis
  namespace: rekor-system
  labels:
    app.kubernetes.io/component: redis
    app.kubernetes.io/instance: scaffold
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: rekor
    helm.sh/chart: rekor-1.0.3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rekor-redis
  template:
    metadata:
      labels:
        app: rekor-redis
        app.kubernetes.io/component: redis
        app.kubernetes.io/instance: scaffold
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: rekor
        helm.sh/chart: rekor-1.0.3
    spec:
      containers:
        - name: rekor-redis
          args:
            - /usr/bin/run-redis
            - --bind
            - 0.0.0.0
            - --appendonly
            - "yes"
          image: {{ redis_image }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379
              hostPort: 6379
              protocol: TCP
          readinessProbe:
            exec:
              command:
                - /usr/bin/run-redis
                - --bind
                - 0.0.0.0
                - --appendonly
                - "yes"
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      securityContext: {}
      serviceAccountName: rekor-redis
      tolerations:
        - effect: NoExecute
          key: node.kubernetes.io/not-ready
          operator: Exists
          tolerationSeconds: 300
        - effect: NoExecute
          key: node.kubernetes.io/unreachable
          operator: Exists
          tolerationSeconds: 300
