apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ tas_single_node_rekor_search_ui_pod }}"
  namespace: rekor-search-ui
  labels:
    app.component: search
    app.instance: scaffold
    app.name: rekor-search-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app.component: search
      app.instance: scaffold
      app.name: rekor-search-ui
  template:
    metadata:
      labels:
        app.component: search
        app.instance: scaffold
        app.name: rekor-search-ui
    spec:
      containers:
        - name: rekor-ui
          image: "{{ tas_single_node_rekor_search_ui_image }}"
          imagePullPolicy: Always
          env:
            - name: NEXT_PUBLIC_REKOR_DEFAULT_DOMAIN
              value: https://rekor.{{ tas_single_node_base_hostname }}
          ports:
            - containerPort: {{ tas_single_node_rekor_search_ui_port | int }}
              protocol: TCP
