apiVersion: apps/v1
kind: Deployment
metadata:
  name: ctlog
  namespace: ctlog-system
  labels:
    app.kubernetes.io/instance: scaffold
    app.kubernetes.io/name: ctlog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ctlog
  template:
    metadata:
      labels:
        app: ctlog
        app.kubernetes.io/instance: scaffold
        app.kubernetes.io/name: ctlog
    spec:
      containers:
        - name: ctlog
          image: {{ ct_server_image }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6962
              protocol: TCP
            - containerPort: 6963
              protocol: TCP
          args:
            - --http_endpoint=0.0.0.0:6962
            - --metrics_endpoint=0.0.0.0:6963
            - --log_config=/config/config
            - --alsologtostderr
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /ctfe-keys
              name: keys
              readOnly: true
            - mountPath: /config
              name: config
              readOnly: true
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      nodeName: minikube
      preemptionPolicy: PreemptLowerPriority
      priority: 0
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsNonRoot: true
        runAsUser: 65533
      serviceAccountName: ctlog
      tolerations:
        - effect: NoExecute
          key: node.kubernetes.io/not-ready
          operator: Exists
          tolerationSeconds: 300
        - effect: NoExecute
          key: node.kubernetes.io/unreachable
          operator: Exists
          tolerationSeconds: 300
      volumes:
        - name: keys
          secret:
            secretName: ctlog-secret
        - name: config
          configMap:
            name: ctlog-config
